[project]
name = "specify-cli"
version = "0.4.0"
description = "Setup tool for Specify spec-driven development projects"
requires-python = ">=3.11"
dependencies = [
    "typer",
    "rich",
    "httpx",
    "platformdirs",
    "readchar",
    "truststore>=0.10.4",
]

[project.scripts]
specify = "specify_cli:main"

[project.urls]
Homepage = "https://github.com/hcnimi/spec-kit"
Repository = "https://github.com/hcnimi/spec-kit"
Issues = "https://github.com/hcnimi/spec-kit/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/specify_cli"]
include = [
    "templates/",
    "src/specify_cli/scripts/**/*.sh",
]
